/* tslint:disable */
/* eslint-disable */
/**
 * Starter App
 * A starter project with a server-rendered SPA architecture.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCheckout
 */
export interface CreateCheckout {
    /**
     * 
     * @type {string}
     * @memberof CreateCheckout
     */
    priceid: string;
}

/**
 * Check if a given object implements the CreateCheckout interface.
 */
export function instanceOfCreateCheckout(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "priceid" in value;

    return isInstance;
}

export function CreateCheckoutFromJSON(json: any): CreateCheckout {
    return CreateCheckoutFromJSONTyped(json, false);
}

export function CreateCheckoutFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCheckout {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'priceid': json['priceid'],
    };
}

export function CreateCheckoutToJSON(value?: CreateCheckout | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'priceid': value.priceid,
    };
}

