/* tslint:disable */
/* eslint-disable */
/**
 * Starter App
 * A starter project with a server-rendered SPA architecture.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductMetadata
 */
export interface ProductMetadata {
    /**
     * 
     * @type {string}
     * @memberof ProductMetadata
     */
    stripeId: string;
    /**
     * 
     * @type {string}
     * @memberof ProductMetadata
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof ProductMetadata
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProductMetadata
     */
    features: Array<string>;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ProductMetadata
     */
    priceDisplays: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof ProductMetadata
     */
    description: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProductMetadata
     */
    isDefault: boolean;
}

/**
 * Check if a given object implements the ProductMetadata interface.
 */
export function instanceOfProductMetadata(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "stripeId" in value;
    isInstance = isInstance && "slug" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "features" in value;
    isInstance = isInstance && "priceDisplays" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "isDefault" in value;

    return isInstance;
}

export function ProductMetadataFromJSON(json: any): ProductMetadata {
    return ProductMetadataFromJSONTyped(json, false);
}

export function ProductMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductMetadata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stripeId': json['stripe_id'],
        'slug': json['slug'],
        'name': json['name'],
        'features': json['features'],
        'priceDisplays': json['price_displays'],
        'description': json['description'],
        'isDefault': json['is_default'],
    };
}

export function ProductMetadataToJSON(value?: ProductMetadata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stripe_id': value.stripeId,
        'slug': value.slug,
        'name': value.name,
        'features': value.features,
        'price_displays': value.priceDisplays,
        'description': value.description,
        'is_default': value.isDefault,
    };
}

