# Generated by Django 3.2.5 on 2021-08-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pegasus_examples', '0003_auto_20191004_0707'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
